version: '3.5'
services:
  api:
    image: api
    hostname: api
    depends_on:
      - rinha-db
    expose:
      - "80"
    build:
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    env_file:
    - .env
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
    networks:
      - internalnetwork

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
    networks:
      - internalnetwork

  rinha-db:
    image: postgres
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'
    environment:
      POSTGRES_PASSWORD: "rinha2023"
      POSTGRES_USER: "userrinha"
      POSTGRES_DB: "mydb"
    ports:
      - "5432:5432"
    # volumes:
    #   - rinha-db-data:/var/lib/postgresql/data
    networks:
      - internalnetwork

networks:
  internalnetwork:

volumes:
  rinha-db-data:
